### ISSUE TITLE
Creamcast_Miso_Soup_House

### ISSUE THREAD

**Issue by chrisasma103** [NaomiMod/Rent-A-Hero-No1#206]
I don't know if this is an error or not, but the woman from the first mission who you save from the "ogre" sends you a mail, but it's labeled as being from "Miso Soup House." I don't know if this is just a weird name that she has or if this is an error.

https://imgur.com/a/PjbeoVj

**Comment by ToddlerPichu** [comment]
As a name "Miso Soup" should be correct, though I am unsure if her name or the NPC appears any other place and states anything else that might contradict that due to localization, so I will double check that before marking issue as closed... it is a joke on consumables as names much like other names such as "Jasmine Tee" are. However the "House" part after does not seem to belong, as it is not part of her name.
