### ISSUE TITLE
GFX_ALIS_NOW_LOADING

### ISSUE THREAD

**Issue by VincentNLOBJ** [NaomiMod/Rent-A-Hero-No1#45]
@VincentNLOBJ  That is curious... are we sure that is the case, as she is still referred to by Alisa written in english in the JP version in the loading screen pictures?
![shot64](https://user-images.githubusercontent.com/41944249/192349620-4eccf968-e816-4e8f-90ec-f3cc3336be4e.png)
Phantasy Star is such a wonderful series though... I could talk about it for hours and it is by far the most time I have ever put into a game series, I would love for that to be accurate

_Originally posted by @ToddlerPichu in https://github.com/NaomiMod/Rent-A-Hero-No1/issues/32#issuecomment-1258426357_

**Comment by ToddlerPichu** [comment]
Since the change in game has been made to Alis officially now... I will put these here also, so they don't get overlooked
![shot330](https://user-images.githubusercontent.com/41944249/193427436-f9c9edfd-a6fd-4ff8-b213-70470ced83af.png)
![shot335](https://user-images.githubusercontent.com/41944249/193427438-363178f9-f07b-4d6e-817a-cd74b5cfcb33.png)

**Comment by VincentNLOBJ** [comment]
I got all of them already, just need to revector text so it will look as sharp as source 👍

**Comment by VincentNLOBJ** [comment]
Done!
