### ISSUE TITLE
A12_Sophia_Thank You Very Much! mail

### ISSUE THREAD

**Issue by ToddlerPichu** [NaomiMod/Rent-A-Hero-No1#68]
Upon completion of bodyguard job you the From: Sophia Sinclair does not match up with previous spellings of her name, except for the instance reported in issue #65 
![shot190](https://user-images.githubusercontent.com/41944249/193075655-4d04d891-6c27-46f4-bfcf-809e0d05ce6d.png)

**Comment by VincentNLOBJ** [comment]
Except "Sofia", I'm not sure about "Hey cute stuff!".
I'm not EN native so it might be a slang?

**Comment by ToddlerPichu** [comment]
I am not sure if it is called slang, but "Hey cute stuff!" seems to be appropriate Sofia was flirting with the hero and this seems like a affectionate pick up line kind of introduction. You can notice the absence of this flirting introduction when comparing it to #69 where she did not have personal interaction flirting with (and also most likely due to age gap)

**Comment by VincentNLOBJ** [comment]
How about this?
![shot190](https://i.imgur.com/i4whSTW.gif)

**Comment by ToddlerPichu** [comment]
The gif makes it a little hard to read in time, but looks fine... the only thing I could see being changed is removing the line "I'll ask you personally"

**Comment by VincentNLOBJ** [comment]
From: Sofia Sinclair 
-----------------------
Hey cute stuff!
Thank you for saving me the
other day!

I'm so happy that I wasn't
kidnapped by those creeps.
I want you to see me again but
as a date rather than as a
bodyguard.
I wonder if I have to ask SECA
first before asking you on a date.

That's too weird...Just forget it!

I'll ask you personally.

Oh well, keep up the good work,
Rent-A-Hero!

**Comment by VincentNLOBJ** [comment]
Xbox version in comparison:

From: Sofia Sinclair
------------------

Thank you for saving me the other
day! I'm so happy that I wasn't
kidnapped by those creeps. I want
you to see me again but as a date
rather than as a bodyguard. I
wonder if I have to ask SECA first
before asking you on a date.

That's too weird. Just forget it.
I'll ask you personally.

**Comment by ToddlerPichu** [comment]
"I'll ask you personally." seems to be a line added in the english translation and I don't think it sounds all that good after "ask SECA before asking you on a date." which still involves asking the player personally. If the line were to be kept in I'd personally changethe SECA line to "I wonder if I have to ask SECA for a date with you, as a job.", I think that gives a much better tonal shift with the next line of "That's too weird... Just forget it!"

JP version for comparison:
PLAYERNAME くん 今回 は 変 な 人 たち から わたし を 助け て くれ て ホント に どうも ありがとう
誘拐 さ れ ず に すん で ホッ と し て ます
今度 は ボディ ガード の お 仕事 じゃ なく プライベート で 会い たい ん だ けど やっぱり 、 「 デート の 相手 を し て ! 」 とか 、 SECA に 仕事 として 依頼 を し なきゃ ダメ な の か な ?
でも 何 か おかしい よ ね 、 そんな の ・･･ 
それ じゃ 、 これから も レンタ ヒーロー の お 仕事 がんばっ て ね

**Comment by ToddlerPichu** [comment]
That is only my thought on it though and I see no harm with keeping it how it is without my input... it is already different from the JP version and the only important thing is that the Sofia/Sophia issue was fixed that I reported on, which it is on the revision you showed me 👍

**Comment by VincentNLOBJ** [comment]
Gotcha! 👍
